- name: configure /etc/hosts
  copy:
    src: ../files/hosts
    dest: /etc/hosts
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
    force: yes
    backup: yes
  become: true

- name: install ssh client config
  copy:
    src: ../files/ssh.cfg
    dest: "/home/{{ ansible_user }}/.ssh/config"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0600
    force: yes
    backup: yes

- name: Disallow root SSH access
  lineinfile:
    dest=/etc/ssh/sshd_config
    regexp="^PermitRootLogin"
    line="PermitRootLogin no"
    state=present
  become: true
  notify:
    - restart sshd

- name: Disallow SSH password authentication
  lineinfile:
    dest=/etc/ssh/sshd_config
    regexp="^PasswordAuthentication"
    line="PasswordAuthentication no"
    state=present
  become: true
  notify:
    - restart sshd

- name: Disallow SSH challenge response authentication
  lineinfile:
    dest=/etc/ssh/sshd_config
    regexp="^ChallengeResponseAuthentication"
    line="ChallengeResponseAuthentication no"
    state=present
  become: true
  notify:
    - restart sshd

- name: Disallow SSH GSS API authentication
  lineinfile:
    dest=/etc/ssh/sshd_config
    regexp="^GSSAPIAuthentication"
    line="GSSAPIAuthentication no"
    state=present
  become: true
  notify:
    - restart sshd

- name: Make sure locale en_US.UTF-8 is in locale.conf
  lineinfile:
    dest=/etc/locale.gen
    regexp="^en_US.UTF-8"
    line="en_US.UTF-8"
    state=present
  become: true

- name: Blacklist the nouveau kernel module
  kernel_blacklist:
    name: nouveau
    blacklist_file: /etc/modprobe.d/blacklist-nouveau.conf
    state: present
  become: true
  notify:
    - rebuild initrd
    - reboot host and wait

- name: upgrade kernel
  apt:
    name: linux-generic-hwe-16.04
    install_recommends: yes
    update_cache: yes
  become: true
  async: 1000
  poll: 10

- name: check if we should reboot the system
  stat:
    path: /var/run/reboot-required
    get_md5: no
  register: rebootfile
  become: true

- name: trigger reboot if previous check succeeded
  command: /bin/true
  when: rebootfile.stat.exists == true
  notify:
    - reboot host and wait

- meta: flush_handlers

- name: make sure the nouveau kernel module is *not* loaded
  modprobe:
    name: nouveau
    state: absent
  become: true

- name: upgrade all packages using apt
  apt:
    upgrade: dist
    update_cache: yes
  become: true
  async: 1000
  poll: 10

- name: install nfs-common and ceph-common
  apt:
    name: nfs-common,ceph-common
  become: true
  async: 1000
  poll: 10

- name: Make rpc-statd.service start with multi-user.target
  shell: systemctl add-wants multi-user.target rpc-statd.service
  register: rpcstatd_install
  changed_when: "'Created symlink' in rpcstatd_install.stdout + rpcstatd_install.stderr"
  become: true

- name: enable and start rpc-statd.service
  systemd:
    name: rpc-statd.service
    state: started
    enabled: yes
  become: true

- name: check if we should reboot the system
  stat:
    path: /var/run/reboot-required
    get_md5: no
  register: rebootfile
  become: true

- name: trigger reboot if previous check succeeded
  command: /bin/true
  when: rebootfile.stat.exists == true
  notify:
    - reboot host and wait

- meta: flush_handlers
