- name: restart docker
  systemd:
    name: docker
    daemon_reload: yes
    state: restarted
  become: true

- name: reboot host
  command: /usr/bin/systemd-run --on-active=10 /bin/systemctl reboot
  async: 0
  poll: 0
  listen: "reboot host and wait"
  become: true

- name: wait for host to become available again
  wait_for_connection:
    delay: 60
    timeout: 600
  listen: "reboot host and wait"
