---
# defaults file for squid

squid_access_log: "daemon:/var/log/squid/access.log squid"
squid_acls:
  - name: illume
    type: src
    argument: 192.168.19.0/24
squid_always_directs: []
squid_cache_peers: []
squid_dns_v4_first: "off"
squid_forwarded_for: "on"
squid_http_access_allow_clients:
  - localhost
  - illume
squid_http_port: 3128
squid_httpd_suppress_version_string: "off"
squid_netdb_filename: "stdio:/var/log/squid/netdb.state"
squid_never_directs: []
squid_pinger_enable: "on"
squid_proxy_only: false
squid_tcp_outgoing_address: ''
squid_via: "on"
squid_visible_hostname: ''
squid_cache_dir: "/var/spool/squid"
squid_cache_size: 140000
squid_maximum_object_size_in_memory: "128 KB"
squid_cache_mem: "512 MB"
squid_minimum_expiry_time: 0
squid_max_filedesc: 8192
squid_maximum_object_size: "4096 MB"
