---
# tasks file for squid

- name: Install squid packages
  become: yes
  apt:
    name: squid
    state: present
    update_cache: yes
  tags:
    - squid

- name: Create Squid configuration file
  become: yes
  template:
    src: squid.conf.j2
    dest: "/etc/squid/squid.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart squid
  tags:
    - squid

- name: Create Squid error page CSS file
  become: yes
  template:
    src: errorpage.css.j2
    dest: "/etc/squid/errorpage.css"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart squid
  tags:
    - squid

- name: Ensure Squid service is started and enabled on boot
  become: yes
  service:
    name: squid
    state: started
    enabled: yes
  tags:
    - squid
