#!/bin/bash

dir=/opt/set-gpu-fans

# we need to launch the X server once for each display
# making each of the PCI IDs the primary device in turn.

# get PCI bus ids of Nvidia cards and convert from hexadecimal to decimal. watch out for the falling toothpicks.
pciid=`lspci  | sed -n -e '/VGA compatib.*NVIDIA/s/^\(..\):\(..\).\(.\).*/printf "PCI:%d:%d:%d\\\\\\\\n" 0x\1 0x\2 0x\3;/p'`
disp=0
for s in `eval ${pciid}`
do \
    cfg=`mktemp /tmp/xorg-XXXXXXXX.conf`
    sed -e s,@GPU_BUS_ID@,${s},    \
        -e s,@SET_GPU_DIR@,${dir}, \
        ${dir}/xorg.conf >> ${cfg}
    # we keep one X server per GPU running indefinitely
    # (if we let the X server die, the fan config does not persist, no matter what else)
    xinit ${dir}/nvscmd -- :${disp} -once -config ${cfg} &
    disp=$((disp+1))
    sleep 10
    rm -f ${cfg}
done

wait


