- name: run rke remove on bastion host
  command: "rke remove --force"
  async: 1000
  poll: 10
  when: inventory_hostname in groups['bastion']

- name: Check for running containers
  shell: 'docker ps -aq'
  changed_when: False
  register: found_containers
  when: inventory_hostname not in groups['bastion'] and inventory_hostname not in groups['proxy']

- name: Stop and remove all running containers
  shell: 'docker stop {{ item }} && docker rm -fv {{ item }}'
  with_items: '{{ found_containers.stdout_lines }}'
  when: inventory_hostname not in groups['bastion'] and inventory_hostname not in groups['proxy'] and found_containers.stdout

- name: reboot host
  command: /usr/bin/systemd-run --on-active=10 /bin/systemctl reboot
  async: 0
  poll: 0
  when: inventory_hostname not in groups['bastion'] and inventory_hostname not in groups['proxy']
  become: true

- name: wait for host to become available again
  wait_for_connection:
    delay: 60
    timeout: 600
  when: inventory_hostname not in groups['bastion'] and inventory_hostname not in groups['proxy']

- name: clean up docker - prune images
  command: "docker container prune -f"
  when: inventory_hostname not in groups['bastion'] and inventory_hostname not in groups['proxy']

- name: clean up docker - prune images
  command: "docker image prune -a -f"
  when: inventory_hostname not in groups['bastion'] and inventory_hostname not in groups['proxy']

- name: enumerate files in /var/lib/kubelet
  find: path=/var/lib/kubelet file_type=file
  register: files
  when: inventory_hostname not in groups['bastion'] and inventory_hostname not in groups['proxy']
  become: true

- name: enumerate directories in /var/lib/kubelet
  find: path=/var/lib/kubelet file_type=directory
  register: directories
  when: inventory_hostname not in groups['bastion'] and inventory_hostname not in groups['proxy']

- name: emptying /var/lib/kubelet
  file:
    state: absent
    path: "{{ item.path }}"
  become: true
  with_items:
    - "{{ files.files }}"
    - "{{ directories.files }}"
  when: inventory_hostname not in groups['bastion'] and inventory_hostname not in groups['proxy']
